server:
  port: ${PORT:3333}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:https://eureka-discovery-service.cfapps.io}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true